Generator
zhike-aion/ABIGenerator pull request #13
Opened 2019-02-26 22:38 UTC by zhike-aion

This PR creates the RandomTest. 
1. Add RandomTest, generating dapp automatically. This method has random number of arguments. The arguments of this method have randum types and random values. This dapp returns the abi-encoded arguments.
2. Also, Deploy, call and verify the randomly generated dapp.

2019-02-27 18:49 UTC, zhike-aion commented
Also, Re-organize the test folder, improve the code structures, etc..

2019-02-27 20:08 UTC, arajasek requested changes
Thanks for working on this! I have some initial requested changes, might have more on a second review.

2019-02-27 20:08 UTC, arajasek commented on test/IntegTest.java
> +
All of the changes to this file are redundant, so this file should not be included as part of the PR.

2019-02-27 20:08 UTC, arajasek commented on test/RandomTest.java
> +import java.io.DataOutputStream;
Unused imports can be taken out.

2019-02-27 20:08 UTC, arajasek commented on test/RandomTest.java
> +        System.out.println(String.format("%s.%s%s --- %s arguments", className , methodName,
I would comment out this `println`, and the ones for the parameters. I think so long as you print out the seed, we should always be able to recreate the random test, which is all we want.

It gets irritating to have very verbose tests.

2019-02-27 20:08 UTC, arajasek commented on test/RandomTest.java
> +
Please insert comments explaining what the generated method(s?) do.

2019-02-27 22:22 UTC, zhike-aion commented on test/RandomTest.java
> +        System.out.println(String.format("%s.%s%s --- %s arguments", className , methodName,
Good point!

2019-02-27 22:22 UTC, zhike-aion commented on test/RandomTest.java
> +import java.io.DataOutputStream;
Good point!

2019-02-27 22:22 UTC, zhike-aion commented on test/IntegTest.java
> +
Good point!

2019-02-28 18:56 UTC, arajasek approved these changes
Thanks for the changes, looks good to me!

2019-02-28 20:25 UTC, merged